# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
fabric_version=0.154.2+26.2
loader_version=0.19.3
loom_version=1.17.14

# Mod options
mod_id=sophisticatedcore
mod_name=Sophisticated Core
mod_license=GNU General Public License v3.0
mod_version=1.2.9.21
mod_group_id=sophisticatedcore
mod_authors=P3pp3rF1y, Salandora
mod_description=A library / shared functionality mod for Sophisticated Storage and Backpacks
mod_credits=Created by P3pp3rF1y. Ported to Fabric by Salandora.
mod_logo_file=SophisticatedCoreFabric.png
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/sophisticated-core-unofficial-fabric-port
mod_issue_tracker_url=https://github.com/goakiller900/SophisticatedCore/issues
mod_sources_url=https://github.com/goakiller900/SophisticatedCore
github_package_url=https://maven.pkg.github.com/goakiller900/SophisticatedCore

# If set to "none" we use the version provided by fabric loader
mixin_extras_version = 0.5.0-beta.3

#publish
curseforge_id=979317
modrinth_project_id=9jxwkYQL
release_type=release
release_versions=26.2

# Dependencies
porting_lib_modules = conditions,core,fluids,item_abilities,lazy_registration,level_events,loot,model_loader,render_types,transfer
porting_lib_version = 3.1.0-beta.47

energy_version = 5.0.0

# Compat
# https://modrinth.com/mod/jei/versions?g=1.21.1&l=fabric
jei_version = 19.21.0.246
# https://modrinth.com/mod/rei/versions?g=1.21.1&l=fabric
rei_version = 16.0.799
# architectury_version = 6.0.37
# https://modrinth.com/mod/emi/versions?g=1.21.1&l=fabric
emi_version = 1.1.16+1.21.1

# https://github.com/Fuzss/forgeconfigapiport/tree/main
forge_config_api_port_version = 26.2.1

# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
jade_version = 5706164

# https://modrinth.com/mod/cloth-config/versions?g=1.21.1&l=fabric
cloth_config_version=15.0.140

# https://www.curseforge.com/minecraft/mc-mods/balm-fabric/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
balm_cf_file_id=5798232
# https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks-fabric/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
crafting_tweaks_cf_file_id=5644048
# https://www.curseforge.com/minecraft/mc-mods/chipped/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
chipped_version=4.0.1

# https://www.curseforge.com/minecraft/mc-mods/malilib/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
malilib_cf_file_id=5647783
# https://www.curseforge.com/minecraft/mc-mods/litematica/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
litematica_cf_file_id=5647809

# Simple Voice Chat
# https://modrinth.com/plugin/simple-voice-chat/versions?l=fabric&g=1.21.1
simple_voice_chat_version=fabric-1.21.1-2.5.24

# AudioPlayer
# https://modrinth.com/mod/audioplayer/versions?l=fabric&g=1.21.1
audioplayer_version=fabric-1.21.1-1.12.0
# https://modrinth.com/mod/admiral/versions?l=fabric&g=1.21.1
admiral_version=0.4.6+1.21.1+fabric

# Trinkets
# https://modrinth.com/mod/trinkets/versions?g=1.21.1&l=fabric
trinkets_version=3.10.0

# What recipe viewer to use ('emi', 'rei', or 'jei'. if you change it, don't push it)
recipe_viewer = emi
